Replaced getenv/putenv with `$_ENV` and unset
googleapis/google-auth-library-php pull request #429
Opened 2023-01-16 14:29 UTC by DracoBlue

The current version of google auth library php uses getenv/putenv to read and set environment variables in php. But the  function putenv is not threadsafe, which made libraries (Dotenv https://github.com/symfony/dotenv/blob/6.2/Dotenv.php#L61 and phpdotenv https://github.com/vlucas/phpdotenv#putenv-and-getenv) to disable putenv support by default. Frameworks like symfony (deprecated in 4.3 https://github.com/symfony/symfony/pull/31062 and removed in 5.0) and also in laravel there was a similiar solution to not use it anymore directly (https://github.com/vlucas/phpdotenv/issues/76).

Thus here is a pull request to change all the ocurences of:

- `getenv($variable)` to `(array_key_exists($variable, $_ENV) ? $_ENV[$variable] : false)`
- `putenv($variable)` to `unset($_ENV[$variable])`
- `putenv($variable . "=")` to `$_ENV[$variable]=''`
- `putenv($variable . "=" . $value)` to `$_ENV[$variable]=$value`

2023-01-17 05:18 UTC, vishwarajanand commented
@DracoBlue thanks for making this PR. I want to check once whether there was any reason for using `getenv/putenv` across all libraries.
If you can, pls fix the commit message according to conventional commit guidelines.

2023-01-17 09:51 UTC, DracoBlue commented
Done!

2023-01-17 16:26 UTC, bshaffer requested changes
@DracoBlue Sorry for the confusing bot message, your previous PR title was correct, and it was just giving a warning to us (the administrators) in case we merged with the _commit message_ instead of the PR title, which was in the incorrect format. I fixed this in #430, so this message will no longer happen.

As for this PR, unfortunately, the changes here break existing implementations. If someone is setting their credentials using `putenv` (as we've instructed them to do), this library would no longer work as expected. This is unacceptable. 
I can see three options:

 1. Wait to make these changes in a v2 version
 2. Check `getenv` first and `_ENV` second. (This seems like it would cause even more issues)
 3. Provide a way (similar to symphony's `usePutenv` function, perhaps even use an environment variable as a flag 😛) to use the threadsafe version, e.g.:

```php
$_ENV['GOOGLE_AUTH_USE_PUTENV']=false
$_ENV['GOOGLE_APPLICATION_CREDENTIALS'] = '/path/to/credentials.json'';
```

There are some other implications of switching from `getenv`/`putenv` that aren't discussed in this PR, along with the implications of these functions not being threadsafe. Do you have any links to discussions of the implications?

2023-01-18 16:36 UTC, DracoBlue commented
> There are some other implications of switching from getenv/putenv that aren't discussed in this PR, along with the implications of these functions not being threadsafe. Do you have any links to discussions of the implications?

I added some more threads related to this to the initial post.

> Check getenv first and _ENV second. (This seems like it would cause even more issues)

I think so, too.

> Provide a way (similar to symphony's usePutenv function, perhaps even use an environment variable as a flag 😛) to use the threadsafe version, e.g.:

I guess for this to be interesting enough to implement, I would suggest I am supplying a test case (I don't have a proper one, yet!) which suffers from the getenv/putenv threadsafety issue - and then we can think about a way to make it possible for those using the frameworks possible to supply the credentials variable in a safe way.

2023-01-25 21:21 UTC, bshaffer commented
I've moved this into a feature request here: https://github.com/googleapis/google-auth-library-php/issues/432
> supplying a test case... which suffers from the getenv/putenv threadsafety issue

Yes! If you have one, or find one, please update the above issue!

I'm closing this for now since we will not be using this implementation.

2023-01-25 21:21 UTC, closed without merging